sudo: required
addons:
  hosts:
  - boundless-test
services:
- docker
env:
  global:
  - PLUGIN_NAME=LDMP
  - secure: CTpzPHpSavbJVuk+Mq2gMOeuw0bbJ4UttuNGRB8JPdoswE4V19P7/9wUPpAK2qKD0KrnXmgH1G+jnUaowsboePcNJHJ5qUscTBr3yM4SBp4W/1YHADgI84BGMv4maQQ25Ix1mtImGEIZ+F4QA4pRHm/8W/xqneXDHficrme6O9gWm/AgL1ook98zGqj2haOwqMWgWPUreuN1/MM8omMR+uBhQ8Pab9GivsLOPE4TjAaGOPUqWoGIlrWADKOrEJegav/ZcY2/f6SQqbnEIKICo2PoSfzDjHeWq8Z/JD4Fs7WoQ3aROI1fvFeG95HXre2WIzUtg354V5Z2JDPula/LVklUBkE1jd8urH7WqFkqztzVquY2Vr3mQmNE67o2HLrzffy4SB3YsNjguPIMemZ0BDmFx7aGldWz+anqQCEy+6j9CNMQ/cHnqom/2ONpuak8aFOojZfrkj46xBWK1KyUCHVe1+e3xAN/NKH0cD6mlYOlZ09UfGqACWn+UcBh05RCjxssGQQxUc39cWsKG1RjNMGgJ4QGfDjZ7LCLJNKj84EsuEVCitrAYUaeoptOWKdpQgbQ/lrdKbbfLVe2x+gb3JHAe73XhbZTi+mSauzAGmJCxaE8XspMh6Tmh4iFvAu9cYKKGjIE5h/l8ad9X69Wn5vBqAkb8mOT5GhjFB+INP8=
  - secure: TYckYXS4aMt0MD2sMb5MMOLs+G6V8QBneCJn1AxCK8A4epmEvGBhucXBfVetzPW1eQFgCe4QozPK4/LD4+3eDylt/1SWWpby7h7KaXCL7ILvYSdTJhi6oCgs5JqrC4In3/ggAUcuOZrBIgcLCuBjQ4XsnDtKhmLr1wQcr9XBSv0jcMVbGC2gO6RtM+3T+hiE7s7TzyZG0z+9/02hGPahy05zhZdpH3G3DfXRbkUDildSqU9Vfw/eUfkTmULByfi3weOoDxKNfFIQgGdUx2s3k6dqM+a2NhPDEYzUvn4icVCim75qjAPDAUkdFSk6/EeTQ2Rnu0mp7cYLAsqWYQFTeFetNZNzixwhzsLzvDZ7Idrg8BuDhnmRff/zHo6yS5OkVb6X9JtPAQc0guCkn4WDz1yqkRMiiHMdvothGvyb65znPk+N0hKCadxSqJiOyqb6fpfGghAH16fTl58Ocvsgmsw+xUF8ttc8QEIbZXPuWGbJTZQSqIKzyW3sSC2DwLLfjLzSWgOz2RetQoWDPI4RPdNYfuy4BnxANJgKZrGcJkK8P+PXPtKbUXrSWZiQfx+ODqCvPpCoeOiExKqAjFjFPqNQW113uN0dInn/bZIrMQQlP3C1ZR2tlk4Vgamtp4JWHan1igtYOiEocpuPeqVi4xYmegvPk1n2/5oFYfLhcRM=
  matrix:
  - QGIS_VERSION_TAG=release PYTHON_EXECUTABLE=python PIP_EXECUTABLE=pip
  - QGIS_VERSION_TAG=master_2 PYTHON_EXECUTABLE=python PIP_EXECUTABLE=pip
  - QGIS_VERSION_TAG=master PYTHON_EXECUTABLE=python3 PIP_EXECUTABLE=pip3
matrix:
  allow_failures:
  - env: QGIS_VERSION_TAG=master PYTHON_EXECUTABLE=python3 PIP_EXECUTABLE=pip3
  - env: QGIS_VERSION_TAG=release PYTHON_EXECUTABLE=python PIP_EXECUTABLE=pip
before_install:
- docker-compose up -d
- docker-compose ps
- sleep 10
- docker-compose exec qgis-testing-environment sh -c "qgis_setup.sh ${PLUGIN_NAME}"
- docker-compose exec qgis-testing-environment sh -c "pip install paver"
- docker-compose exec qgis-testing-environment sh -c "pip install boto3"
script:
- docker-compose exec qgis-testing-environment sh -c "cd /tests_directory && paver setup && paver package --tests"
- docker-compose exec qgis-testing-environment sh -c "cd /tests_directory && paver deploy"
