sudo: required
addons:
  hosts:
  - boundless-test
services:
- docker
env:
  global:
  - PLUGIN_NAME=LDMP
  - secure: SS0PQlPaahZCHSPJ10mWtF+LY1hstTZNJZV8x9r6gYem2PGgwsKqZ/s+go21yt6d/E/Q/zM22xnPeJamXhsT3P43iYOkXUoNKkUIoxIujvm9JMa9GUu2VQM/XXK4nm9pFmMSs+CDazOfUKT4w47N3x7aLO1IL4n7je/0k+PllFqtFiZNjD4cL7Ew/w/cJwoM8AMPE5wd9PwhIAXMjm9HLGyyoqn0/HtAVy93VIvSiS+NA4Umal4bpg073LYONZ+SI0I5qUKZrcF40MtounmATeIakdcRZdzSVfz7ml5/JMReG8tZzEGpVSd9bwQySu1yaC8RS8YQ4YzvIA6fnis5SPwp4tQ4Sc+1Z44TsQNuhvDSxtcKe8zoscXpTCRm4fngtCWexhpUQcfr3j9UQXldJ1RSU+dcV0Uaq/VFi9pv4xtBg8hDAyusW6pm2oYUA1zBb69GDYFngAP5pqx3xoMC3qP7U3dZgX128Ro2Mduyl7aadTtMB13/oKll9xNWdqijothmFt/ff1su8CUDRq3fAouAavKDP3UOuv0bcxyTRjYFGMd9gO9I49QNnYnIi5KGqDu12pfd6yLby1tv2DFIGNuc3T7Lva5o2rpzOGvgL9ju0OzGdaSz4HpCiR+cD8BgCyV0R5Vu3Rvq4GO4WjT6uBL07FWBhm0tRSP0DggY6Gg=
  - secure: Aofa6Z43I7IGePlK4r5oKbKGz8ILprdKQospOK9mFzCfs6ngKhLS0gBeDox3nMzBQu/tWoGO9H1b2AV6rCXHy3on+klprQNZyaDDcB397PDxs2bs3VFG+rEHBwDL8EVwxikqg9YloJwusKkDcOmgqWod1AJVpi/FPRXyIj6DtB26ffN5gMl4T9LxFwMUJ5SVLSm2uZjTTDZJjrozFye3LLig/iYEoPhcHxa6YXuV8Ur5otucDPN/Okr67TwIzh0MTqwc24ySavNQqvb7384i7d766WAkq+T+/szaHXAa94CU4vXmHYLXclPJnC06WgBb/T7vJJZIrkHrPyC5oiHjPnmXRSeGU4rvTaoJNR/Zrd4htLN1e6kqjFx35me4VU75EVfSYzLKQODILEUbbn38ElsYN4PAkklFdi50s2+TlC+txWqEZfpOd6jrd1460hl2OsC+4ancew5jh6wmygQQgy8gWB+TsG6OAZpu4bX2JhaUZc0tV2umrEJiC1+i7wc6E0oRI7H1GuHV7rl5dhqY3Tc//bMKrq9no9l7ij2SlTMw8F7Ta0OJ1SdNJSfAftYt4ZHLU35xAOJHWeu5RABCTzk5BUBswO8BFO6cvztPkGhcPqBJIgdxERAoS98K9+8p4nNcyHfaKFTH+D8ynayIjLSjB6c45azMqpFDq0YsGNg=
  matrix:
  - QGIS_VERSION_TAG=release PYTHON_EXECUTABLE=python PIP_EXECUTABLE=pip
  - QGIS_VERSION_TAG=master_2 PYTHON_EXECUTABLE=python PIP_EXECUTABLE=pip
  - QGIS_VERSION_TAG=master PYTHON_EXECUTABLE=python3 PIP_EXECUTABLE=pip3
matrix:
  allow_failures:
  - env: QGIS_VERSION_TAG=master PYTHON_EXECUTABLE=python3 PIP_EXECUTABLE=pip3
  - env: QGIS_VERSION_TAG=release PYTHON_EXECUTABLE=python PIP_EXECUTABLE=pip
before_install:
- docker-compose up -d
- docker-compose ps
- sleep 10
- docker-compose exec qgis-testing-environment sh -c "qgis_setup.sh ${PLUGIN_NAME}"
- docker-compose exec qgis-testing-environment sh -c "pip install paver"
- docker-compose exec qgis-testing-environment sh -c "pip install boto3"
script:
- docker-compose exec qgis-testing-environment sh -c "cd /tests_directory && paver
  setup && paver package --tests && paver deploy"
