sudo: required
services:
    - docker
env:
  global:
    - PLUGIN_NAME=LDMP
  matrix:
    - QGIS_VERSION_TAG=master
    - QGIS_VERSION_TAG=release
matrix:
    allow_failures:
    - env QGIS_VERSION_TAG=master
before_install:
    - docker-compose up -d
    - docker-compose ps
    - sleep 10
    - docker-compose exec qgis-testing-environment sh -c "qgis_setup.sh ${PLUGIN_NAME}"
    - docker-compose exec qgis-testing-environment sh -c "pip install paver"
script:
    - docker-compose exec qgis-testing-environment sh -c "cd /tests_directory && paver setup && paver package --tests"
    - docker version
    - docker-compose version
    # Run the unit tests
    # This plugin has not yet any unit tests
    - docker-compose exec qgis-testing-environment sh -c "echo '${PLUGIN_NAME} has no unit tests yet, please create them and add here'"
