version: '2'

services:
    qgis-testing-environment:
        image: boundlessgeo/qgis-testing-environment:${QGIS_VERSION_TAG}
        volumes:
            - ./:/tests_directory
        environment:
            DISPLAY: ':99'
            QT_X11_NO_MITSHM: '1'
