version: '2'

services:
    qgis-testing-environment:
        volumes:
            - ./:/tests_directory
        environment:
            DISPLAY: ':99'
            QT_X11_NO_MITSHM: '1'
        build:
            context: .
